functionsDirectory = "/opt/build/repo/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/opt/build/repo/public"
publishOrigin = "config"
functions = "/opt/build/repo/netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[database]

  [database.migrations]
  path = "/opt/build/repo/netlify/database/migrations"

[functions]

  [functions."*"]
  external_node_modules = [
    "@netlify/database"
  ]
  node_bundler = "esbuild"